package com.pingithefrosty.oktapp.collections;

import org.springframework.stereotype.Component;

import java.util.Arrays;
import java.util.List;

@Component
public class Telepulesek {

  private List<String> telepulesTypes;

  public Telepulesek() {
    telepulesTypes = Arrays.asList("Aba",
        "Abaújkér",
        "Abaújszántó",
        "Abony",
        "Ács",
        "Adony",
        "Ajka",
        "Alsózsolca",
        "Ásotthalom",
        "Aszód",
        "Bábolna",
        "Bácsalmás",
        "Baja",
        "Baktalórántháza",
        "Balassagyarmat",
        "Balatonalmádi",
        "Balatonfüred",
        "Balatonfuzfo",
        "Balmazújváros",
        "Barcs",
        "Bátaszék",
        "Bátonyterenye",
        "Battonya",
        "Békés",
        "Békéscsaba",
        "Bercel",
        "Berettyóújfalu",
        "Berkesd",
        "Bicske",
        "Biharkeresztes",
        "Biri",
        "Bocs",
        "Bodajk",
        "Bóly",
        "Bonyhád",
        "Budakeszi",
        "Budaörs",
        "Budapest",
        "Budapest I. kerület",
        "Budapest II. kerület",
        "Budapest III. kerület",
        "Budapest IV. kerület",
        "Budapest IX. kerület",
        "Budapest V. kerület",
        "Budapest VI. kerület",
        "Budapest VII. kerület",
        "Budapest VIII. kerület",
        "Budapest X. kerület",
        "Budapest XI. kerület",
        "Budapest XII. kerület",
        "Budapest XIII. kerület",
        "Budapest XIV. kerület",
        "Budapest XIX. kerület",
        "Budapest XV. kerület",
        "Budapest XVI. kerület",
        "Budapest XVII. kerület",
        "Budapest XVIII. kerület",
        "Budapest XX. kerület",
        "Budapest XXI. kerület",
        "Budapest XXII. kerület",
        "Budapest XXIII. kerület",
        "Buják",
        "Bük",
        "Cegléd",
        "Celldömölk",
        "Csapi",
        "Csenger",
        "Csepreg",
        "Csobánka",
        "Csongrád",
        "Csorna",
        "Csurgó",
        "Dabas",
        "Debrecen",
        "Demecser",
        "Derecske",
        "Devecser",
        "Dombóvár",
        "Dombrád",
        "Dorog",
        "Dunaföldvár",
        "Dunaharaszti",
        "Dunakeszi",
        "Dunaújváros",
        "Dunavecse",
        "Edelény",
        "Eger",
        "Egyházasgerge",
        "Emod",
        "Encs",
        "Enying",
        "Érd",
        "Esztergom",
        "Fegyvernek",
        "Fehérgyarmat",
        "Felcsút",
        "Fertod",
        "Fonyód",
        "Fót",
        "Füzesabony",
        "Gárdony",
        "Göd",
        "Gödöllo",
        "Gyál",
        "Gyomaendrod",
        "Gyömro",
        "Gyöngyös",
        "Gyönk",
        "Gyor",
        "Gyula",
        "Gyulaháza",
        "Gyüre",
        "Hajdúböszörmény",
        "Hajdúdorog",
        "Hajdúhadház",
        "Hajdúnánás",
        "Hajdúszoboszló",
        "Halásztelek",
        "Hatvan",
        "Herend",
        "Heves",
        "Hévíz",
        "Hódmezovásárhely",
        "Hogyész",
        "Ibrány",
        "Isaszeg",
        "Jánoshalma",
        "Jászapáti",
        "Jászárokszállás",
        "Jászberény",
        "Kadarkút",
        "Kalocsa",
        "Kápolnásnyék",
        "Kaposvár",
        "Kapuvár",
        "Karcag",
        "Kazincbarcika",
        "Kecel",
        "Kecskemét",
        "Kék",
        "Kenderes",
        "Keszthely",
        "Kétegyháza",
        "Kisbér",
        "Kiskorös",
        "Kiskunfélegyháza",
        "Kiskunhalas",
        "Kiskunlacháza",
        "Kiskunmajsa",
        "Kistarcsa",
        "Kistelek",
        "Kisújszállás",
        "Kisvárda",
        "Komárom",
        "Komló",
        "Körmend",
        "Koszeg",
        "Kunhegyes",
        "Kunszentmárton",
        "Kunszentmiklós",
        "Lak",
        "Lenti",
        "Lorinci",
        "Magyarhertelend",
        "Makó",
        "Marcali",
        "Martfu",
        "Mátészalka",
        "Megyaszó",
        "Mezoberény",
        "Mezocsát",
        "Mezohegyes",
        "Mezokovácsháza",
        "Mezokövesd",
        "Mezoörs",
        "Mezotúr",
        "Miskolc",
        "Mohács",
        "Monor",
        "Mór",
        "Mórahalom",
        "Mosonmagyaróvár",
        "Nádudvar",
        "Nagyatád",
        "Nagybajom",
        "Nagyberény",
        "Nagyecsed",
        "Nagykálló",
        "Nagykanizsa",
        "Nagykáta",
        "Nagykorös",
        "Nemesgulács",
        "Nemesvámos",
        "Neszmély",
        "Nógrádsáp",
        "Nyergesújfalu",
        "Nyíradony",
        "Nyírbátor",
        "Nyíregyháza",
        "Ócsa",
        "Örkény",
        "Orosháza",
        "Oroszlány",
        "Ózd",
        "Paks",
        "Pannonhalma",
        "Pápa",
        "Pásztó",
        "Pécel",
        "Pécs",
        "Pécsvárad",
        "Pétfürdo",
        "Piliscsaba",
        "Pilisszentlászló",
        "Pilisvörösvár",
        "Polgár",
        "Pomáz",
        "Püspökladány",
        "Pusztaszabolcs",
        "Putnok",
        "Ráckeve",
        "Rakamaz",
        "Sajóecseg",
        "Sajókaza",
        "Sajószentpéter",
        "Salgótarján",
        "Sárbogárd",
        "Sarkad",
        "Sárospatak",
        "Sárvár",
        "Sásd",
        "Sáta",
        "Sátoraljaújhely",
        "Seregélyes",
        "Siklós",
        "Simontornya",
        "Siófok",
        "Solt",
        "Solymár",
        "Somogyzsitfa",
        "Sopron",
        "Sümeg",
        "Szakoly",
        "Szarvas",
        "Százhalombatta",
        "Szécsény",
        "Szeged",
        "Szeghalom",
        "Székesfehérvár",
        "Szekszárd",
        "Szentendre",
        "Szentes",
        "Szentgotthárd",
        "Szerencs",
        "Szigetszentmikló",
        "Szigetszentmiklós",
        "Szigetvár",
        "Szikszó",
        "Szirák",
        "Szob",
        "Szolnok",
        "Szombathely",
        "Tamási",
        "Tapolca",
        "Tata",
        "Tatabánya",
        "Tiszaföldvár",
        "Tiszafüred",
        "Tiszakécske",
        "Tiszalök",
        "Tiszaújváros",
        "Tiszavasvári",
        "Tokaj",
        "Tolna",
        "Törökbálint",
        "Törökszentmiklós",
        "Tótkomlós",
        "Túrkeve",
        "Újfehértó",
        "Újszász",
        "Vác",
        "Vajszló",
        "Várpalota",
        "Vásárosnamény",
        "Vasvár",
        "Vecsés",
        "Velence",
        "Veszprém",
        "Záhony",
        "Zalaegerszeg",
        "Zalaszentgrót",
        "Zánka",
        "Zirc",
        "Zsámbék");
  }

  public List<String> getTelepulesTypes() {
    return telepulesTypes;
  }
}
